# Generated by Django 3.2.12 on 2022-04-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0006_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
